name: Build and Test C Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build project
        run: make all

      - name: Make test.sh executable
        run: chmod +x ./test.sh

      - name: Make interative.sh executable
        run: chmod +x ./interactive.sh

      - name: Make network.sh executable
        run: chmod +x ./network.sh

      - name: Install valgrind
        run: sudo apt-get install valgrind

      - name: Run tests
        run: ./test.sh
